require("keybindings.global.awesome")
require("keybindings.global.focus")
require("keybindings.global.launcher")
require("keybindings.global.layout")
require("keybindings.global.media")
require("keybindings.global.brightness")
require("keybindings.global.tag")
