name: CI

on:
  push:
    branches:
      - master
      - github-actions          # To test changes related to GitHub Actions.
      - ci                      # To test all CI changes.
    paths-ignore:
      - '*.md'
      - doc/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - doc/**

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          # - ubuntu-18.04
          - ubuntu-20.04
        emacs-version:
          # - '25.3'
          # - '26.3'
          - '27.2'
        include:
          # # Older Emacs binaries for Windows don't have dynamic modules enabled.
          # - os: windows-2016
          #   emacs-version: '27.2'
          - os: windows-2019
            emacs-version: '27.2'
          - os: macos-11
            emacs-version: '27.2'
            # Cross build
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        run: |
          rustup install stable
          rustc -Vv
          cargo -V
      - name: Set up Rust's cross-build target
        if: matrix.target
        run: |
          rustup target add ${{ matrix.target }}

      # Using a specific commit hash to fix this https://github.com/purcell/setup-emacs/issues/24.
      - uses: purcell/setup-emacs@b56a75706e31e22d474357c77fb25ce73be2973a
        if: runner.os != 'Windows'
        with:
          version: ${{ matrix.emacs-version }}
      # Seems like the Emacs archive from GNU's FTP uses its own outdated bundle of CA certs, which
      # wouldn't include the new LetsEncrypt's root CA cert, which is used by MELPA, among others.
      # So we use mingw64's Emacs instead. TODO: Switch back whenever possible.
      - name: Install Emacs (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:MSYS_PATH = "$env:CD\ci-tools\msys2"
          choco install msys2 --params="/InstallDir:$env:MSYS_PATH /NoPath"
          $env:PATH = "$env:MSYS_PATH\usr\bin;" + $env:PATH
          pacman -S --noconfirm --needed mingw-w64-x86_64-emacs
          echo "$env:MSYS_PATH\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf-8 -Append
      # - uses: jcs090218/setup-emacs-windows@v4
      #   if: runner.os == 'Windows'
      #   with:
      #     version: ${{ matrix.emacs-version }}

      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: .github/script/setup-cask

      - run: bin/setup
      - run: bin/build -target "${{ matrix.target }}"

      - run: bin/inspect-binaries
        continue-on-error: true

      - name: Install tree-sitter CLI
        if: ${{ !matrix.target }}
        run: npm install -g tree-sitter-cli@0.19.3
      - run: bin/test
        if: ${{ !matrix.target }}
      - run: bin/test bench
        if: ${{ !matrix.target }}
